Humanagent
tpeter002/cyberoffice pull request #18
Opened 2024-05-12 17:08 UTC by Vbarnabas

2024-05-14 18:59 UTC, csumpasd requested changes
fullosnak tunik, de a megbeszelteket meg nem implementalja, azok nagyon kellenenek:

1, a `human_ready` perceptet kuldje el a mainframenek startupnal
2, hasznalja a printert napi rutin reszekent (lathato a mainframe.asl-ben hogy ezt hogy lehet, a `print`, a `done`, es az `error` lehet erdekes neked)
3, ha a mainframetol kap egy `go_fix(Errorer, X, Y)` perceptet, akkor menjen a megjelolt koordinatakra (pontosabban ameddig tud, mert ott az Errorer, avagy a hibat dobo agent van), es az Errorernek kuldjon ki egy `fixed` perceptet, majd terjen vissza a napi rutinjara. (itt amugy @pethodoma  majd magadnal nevezd at pls a `repair`-t `fixed`-re, es akkor konzisztens a megjavithato dolgok kozt).
4, valahogy kuldje el a mainframenek a napi rutinjat, hogy szamon tudja tartani a specnek megfeleloen (kerlek ird meg nekem hogy mit implementaljak ehhez, vagy hogy szeretned)

amugy nice work!

2024-05-14 19:14 UTC, Vbarnabas commented
de legyszi mergeljetek es akk egybe le tudom huzni nezni kivel hogy beszelhetek ilyenek

2024-05-14 20:17 UTC, csumpasd approved these changes
alr :D

2024-05-14 20:17 UTC, merged

2024-05-15 18:15 UTC, tpeter002 commented
Ja akkor ezzel mi a helyzet? Mikor jön a compatibility test? @Vbarnabas